# -*- coding: utf-8 -*-
"""autogen_rag_complex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8cKLCCd7jyptazN13zDcVJOgT_fVugx
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install "pyautogen>=0.2.3" docker

import os
import json
from google.colab import userdata
open_ai_key = userdata.get('OPENAI_API_KEY')

config_list = [
    {
        'model': 'gpt-4-turbo-preview',
        'api_key': open_ai_key,
    }
]

config_json = json.dumps(config_list)

print(config_json)
os.environ['OAI_CONFIG_LIST'] = config_json

import autogen

config_list = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={
        "model": ["gpt4", "gpt-4-turbo-preview", "gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314", "gpt-4-vision-preview"],
    },
)

llm_config = {
    "timeout": 600,
    "cache_seed": 42,
    "config_list": config_list,
    "temperature": 0,
}

# create an AssistantAgent instance named "assistant"
assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config=llm_config,
)
# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="TERMINATE",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={
        "work_dir": "web",
        "use_docker": False,
    },  # Please set use_docker=True if docker is available to run the generated code. Using docker is safer than running the generated code directly.
    llm_config=llm_config,
    system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
Otherwise, reply CONTINUE, or the reason why the task is not solved yet.""",
)

# the assistant receives a message from the user, which contains the task description
user_proxy.initiate_chat(
    assistant,
    message="""
Please map latest SOC2 criteria defined in this document https://soc-comply.com/pdf/SOC2_description_criteria.pdf to ISO/IEC 27001:2022 management clauses defined in https://soc-comply.com/pdf/ISO_IEC_27001_2022.pdf?
""",
)